### ISSUE TITLE
Render List Of Links

### ISSUE THREAD

**Issue by MiErnst** [B1naryStudio/md-chips#1]
Hi,
It would be nice if it could also be used also to render a list of "users" as simple links (for example each item has to have an url propery). Also the input field should be optional.
As stated in the design specification:

> **Touching them invokes the full entity view in a card or full screen view** or invokes a menu of options related to that chip’s entity.

Maybe it should also be possible to provide a directive property with a function reference name. The function could then be invoked with the item as argument when a chip is clicked..

Btw:
Greate idea. and thanks for sharingI just searched for such a component. Do you plan to integrate this work into the https://material.angularjs.org project?

Other question. What will be the license of this project?

**Comment by BogdanRusinka** [comment]
Hi, thank you for the comment.
The license is MIT, it's already added. Integrating it to  https://material.angularjs.org  would be great, but I don't think they will take it:).
What do you mean by simple links, could you explain?  Optional input, what does that also mean? 
Directive property for callback sound good. Maybe it will be implemented soon.

**Comment by MiErnst** [comment]
Hi,
what I mean is to render them just as a list of links, like a list of authors of a blog entry. When one of them is clicked, the profile of the author will be opened (full screen or in a card). As the list of authors is fixed, they don't need this input field.

When writing a email like in your example, the input field is required to enter the email recipients. When displaying a send email in view mode I don't want to display an input field as I could not add recipients to an already send email.

Sorry I have overseen the license in the md file. Typically there is a LICENSE.txt in the root of the project.

**Comment by BogdanRusinka** [comment]
I understood what you mean, that sounds interesting. Thank you for proposition, maybe it will be implemented soon

**Comment by gustavohenke** [comment]
> Integrating it to https://material.angularjs.org would be great, but I don't think they will take it:).

Tests and accessibility are huge steps for this to happen!

**Comment by BogdanRusinka** [comment]
Currently available in v0.2.4
