### ISSUE TITLE
Dropdown Not closing in IE11

### ISSUE THREAD

**Issue by SriramaDanturthi** [B1naryStudio/md-chips#3]
The Drop Down is Not At all Closing in ie 11 and Throwing an Exception

![image](https://cloud.githubusercontent.com/assets/4466654/6513759/6063aac6-c3a3-11e4-9d5e-81048457d1df.png)
![image](https://cloud.githubusercontent.com/assets/4466654/6513774/7c428e24-c3a3-11e4-90b2-95d650ec843e.png)

**Comment by BogdanRusinka** [comment]
fixed
