### ISSUE TITLE
Dynamic Collection

### ISSUE THREAD

**Issue by NBAMj** [B1naryStudio/md-chips#6]
Is it possible to have a dynamic collection that is asynchronously loaded?

**Comment by zacharynevin** [comment]
+1

**Comment by BogdanRusinka** [comment]
Currently it's unavailable, but it will be implemented soon

**Comment by BogdanRusinka** [comment]
This directive is designed for mobile apps mostly, so it will work fine with already predefined data such as contacts and so on. That's why suggested feature won't be provided in current directive. If this functionality is necessary it can be implemented in your controller or service.
