### ISSUE TITLE
Readonly Issue

### ISSUE THREAD

**Issue by mrfaizanhaider** [B1naryStudio/md-chips#8]
can we use readonly attributes for chip???

**Comment by BogdanRusinka** [comment]
Hi, @mrfaizanhaider )

What should this attribute do? Should it block any input activity for the whole directive?

**Comment by mrfaizanhaider** [comment]
yes

**Comment by mrfaizanhaider** [comment]
it is possible?

**Comment by BogdanRusinka** [comment]
@mrfaizanhaider , currently it is not possible, but it will be implemented soon

**Comment by mrfaizanhaider** [comment]
can we disable input field???

**Comment by BogdanRusinka** [comment]
Not yet, but soon it will be possible

**Comment by BogdanRusinka** [comment]
Implemented. Available through [disabled='true'] attribute starting v0.2.2
